apiVersion: v1
kind: Namespace
metadata:
  name:  network-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-manager
  namespace: network-system
  labels:
    control-plane: network-manager
spec:
  selector:
    matchLabels:
      control-plane: network-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: network-manager
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
      serviceAccountName: network-manager
      containers:
      - command:
        - /ks-network
        args:
          - -v=4
          - np-provider=calico
          - datastore-type=k8s
        image: network:latest
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: net-role-binding
  namespace: network-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-manager
subjects:
- kind: ServiceAccount
  name: network-manager

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-manager