bases:
- ../crds

resources:
  - network.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml

generatorOptions:
   disableNameSuffixHash: true

secretGenerator:
  - name: calico-etcd-secrets
    files:
    - etcd-ca=etcd/ca
    - etcd-key=etcd/key
    - etcd-cert=etcd/crt
    type: Opaque

patchesStrategicMerge:
  - patch_image_name.yaml

namespace: network-test-f22e8ea9
